### ISSUE TITLE
Include Whitespace and Comment tokens in Lexer

### ISSUE THREAD

**Issue by shannah** [mirah/mirah-parser#14]
Currently the MirahLexer skips whitespace and comments.  Sometimes we may want this information when we are lexing a file.  

Propose adding an option to include whitespace and comment tokens.

More information at https://groups.google.com/d/msg/mirah/YBnJTbM8HZc/yietPPHENvgJ

**Comment by baroquebobcat** [comment]
done. It's possible that the current mirah-parser jar in mirah/mirah doesn't have it right now, but that will be fixed before the next release.
