### ISSUE TITLE
Cannot specify fully qualified types

### ISSUE THREAD

**Issue by felixvf** [mirah/mirah-parser#23]
```bash
# mirah -e 'def foo(a:java::util::Collection); puts a; end'
DashE:1:

ERROR: expected tRParen before 'a:java::util:'
def foo(a:java::util::Collection); puts a; end
        ^
DashE failed to parse.
1 errors
# mirah -e 'def foo(a:java.util.Collection); puts a; end'
DashE:1:

ERROR: expected tRParen before 'a:java.util.C'
def foo(a:java.util.Collection); puts a; end
        ^
DashE failed to parse.
1 errors
# mirah -e 'def foo(a:Collection); puts a; end'
DashE:1:

ERROR: Cannot find class Collection
def foo(a:Collection); puts a; end
        ^^^^^^^^^^^^
1 errors
# mirah -e 'def foo(a); puts a; end'
DashE:1:

ERROR: Does not override a method from a supertype.
def foo(a); puts a; end
        ^
1 errors
```

At least the first or the second form of specifying types in a fully qualiified way should work.

Specifying fully qualified types is necessary when writing macros, as the non-fully-qualified types of a macro are evaluated in the context of the macro caller, not in the context of the macro source code (which forces the macro caller to import a type which is actually not literally referenced by the macro caller).

**Comment by baroquebobcat** [comment]
Mirah allows for imports almost anywhere, ala scala. So, the common way to handle this is to import the type in the quoted block. That said, type declarations should support fully qualified names.

**Comment by felixvf** [comment]
Fixed.
